server:
  port: 8099

spring:

  config:
    import: optional:classpath:env.properties
  application:
    name: chat

  profiles:
    active: deploy

  data:
    mongodb:
      uri: ${MONGO_KEY}

  kafka:
    bootstrap-servers: localhost:9090
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        spring.json.trusted.packages: "com.example.chat.*, io.devground.*"
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        enable.idempotence: true
        allow.auto.create.topics: false

    consumer:
      group-id: dbay-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: io.devground.dbay.*, io.devground.core.*, com.example.chat.*
        allow.auto.create.topics: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: chat
    non-secure-port: 8090
    metadata-map:
      port: 8090

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.batch: INFO

custom:
  kafka:
    config:
      topic-partitions: 1
      topic-replications: 1

feign:
  product-service:
    url: http://localhost:8080
  user-service:
    url: http://localhost:18080

chats:
  event:
    topic:
      chat: chats-chat-events
  command:
    topic:
      chat: chats-chat-command
