server:
  port: 8090

spring:
  config:
    import: optional:classpath:env.properties
  application:
    name: chat

  data:
    mongodb:
      uri: ${MONGO_KEY}

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: chat
    non-secure-port: 8090
    metadata-map:
      port: 8090

feign:
  product-service:
    url: http://product-service:8086
  user-service:
    url: http://user-service:18080
