server:
  port: 8001

spring:
  application:
    name: user

  config:
    import: optional:classpath:env:properties

#  jpa:
#    hibernate:
#      #      default_batch_fetch_size: 500
#      #      format_sql: true
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: ${MARIA_DB_URL}
#    username: ${MARIA_DB_USERNAME}
#    password: ${MAIRA_DB_PASSWORD}
  datasource:
    url: jdbc:h2:./dbay-user;MODE=MYSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 500
        format_sql: true

  data:
    redis:
      port: 6379
      host: localhost

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_EMAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers:
      - localhost:9092
#      - localhost:9094
#      - localhost:9096

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all

      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        enable.idempotence: true
        allow.auto.create.topics: false

    consumer:
      group-id: accounts-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    properties:
      spring.json.trusted.packages: com.example.*, io.devground.core.*
      allow.auto.create.topics: false


users:
  config:
    topic-partitions: 1
    topic-replications: 1

  commands:
    topic:
      join: users-join-commands

  events:
    topic:
      join: users-join-events

deposits:
  commands:
    topic:
      join: deposits-join-commands

  events:
    topic:
      join: deposits-join-events

carts:
  commands:
    topic:
      join: carts-join-commands

  events:
    topic:
      join: carts-join-events

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.batch: INFO
    org.springframework.kafka: debug

custom:
  jwt:
    secrets:
      app-key: BBpgN9RJg1nYobpf7KHfJUaoiWSO-gD9EiEApPkV1rWJmH0vAVjMT2Pn-MtaaeElM7GFN88aQFl7d9adK_hB9w



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: "${spring.application.name}:${server.port}:${random.uuid}"