spring:
  application:
    name: user-service

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  kafka:
    bootstrap-servers:
      - localhost:9092

  data:
    mongodb:
      uri: ${MONGO_KEY}
      database: chat

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIA_DB_URL}
    username: ${MARIA_DB_USERNAME}
    password: ${MARIA_DB_PASSWORD}


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: "${spring.application.name}:${server.port}:${random.uuid}"
    prefer-ip-address: false
    hostname: localhost
    non-secure-port: ${server.port}

feign:
  product-service:
    url: http://localhost:8080
  user-service:
    url: http://localhost:18080
