spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/dbay_user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234

  kafka:
    bootstrap-servers:
      - localhost:9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: localhost
<<<<<<< HEAD
    non-secure-port: 18080
=======
    non-secure-port: 8082

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
>>>>>>> 82715b2 ([FIX] 운영 환경에서의 Swagger 버그 수정)
