spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbay_user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234


  data:
    redis:
      port: 6379
      host: localhost

  kafka:
    bootstrap-servers:
      - localhost:9092
    #      - localhost:9094
    #      - localhost:9096

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/