apiVersion: apps/v1

kind: Deployment

metadata:
  name: image-service
  labels:
    app: image-service

spec:
  replicas: 1

  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      app: image-service

  template:
    metadata:
      name: image-service
      labels:
        app: image-service

    spec:
      containers:
        - name: image
          image: jihei1/image
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: image-configmap
            - secretRef:
                name: image-secret
