apiVersion: apps/v1

kind: Deployment

metadata:
  name: nginx-proxy-manager
  labels:
    app: nginx-proxy-manager

spec:

  replicas: 1

  selector:
    matchLabels:
      app: nginx-proxy-manager

  template:
    metadata:
      labels:
        app: nginx-proxy-manager

    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: tls-cert
              mountPath: /etc/letsencrypt/live/dbay.site/fullchain.pem
              subPath: tls.crt
              readOnly: true
            - name: tls-cert
              mountPath: /etc/letsencrypt/live/dbay.site/privkey.pem
              subPath: tls.key
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: tls-cert
          secret:
            secretName: dbay-tls-secret