server:
  port: 8082

spring:
  application:
    name: deposit

#  profiles:
#    active: local

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
<<<<<<< HEAD
=======
        dialect: org.hibernate.dialect.H2Dialect
>>>>>>> cfbedd3 ([REFACTOR] Deposit MSA모듈 분리)
        default_batch_fetch_size: 500
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  batch:
    jdbc:
<<<<<<< HEAD
=======
      # always : ??, embedded : ?? DB ??? ??, never : ?? ???? ??
>>>>>>> cfbedd3 ([REFACTOR] Deposit MSA모듈 분리)
      initialize-schema: never

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        enable.idempotence: true
        allow.auto.create.topics: false

    consumer:
      group-id: dbay-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: io.devground.dbay.*, io.devground.core.*
        allow.auto.create.topics: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: deposit
    non-secure-port: 8082
    metadata-map:
      port: 8082

deposits:
  event:
    topic:
      join: deposits-join-events
      purchase: deposits-purchase-events
      name: deposits-events
  command:
    topic:
      join: deposits-join-commands
      purchase: deposits-purchase-commands
      name: deposits-commands

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.batch: INFO

<<<<<<< HEAD
=======
#external:
#  openfeign-url: http://localhost:8080

>>>>>>> cfbedd3 ([REFACTOR] Deposit MSA모듈 분리)
custom:
  kafka:
    config:
      topic-partitions: 1
      topic-replications: 1
