spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

  elasticsearch:
    uris: http://localhost:9200

  docker:
    compose:
      skip:
        in-tests: false
      enabled: true
      file: docker/docker-compose-test.yml
      profiles:
        active: product
      readiness:
        timeout: 2m
      lifecycle-management: start-and-stop
      start:
        command: up
      stop:
        command: down
        timeout: 1m

  ai:
    vectorstore:
      elasticsearch:
        dimensions: 8
    openai:
      embedding:
        options:
          dimensions: 8

  cloud:
    aws:
      s3:
        enabled: false