server:
  port: 8086

spring:
  application:
    name: product

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/dbay_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mysqlId
    password: mysqlPwd

  profiles:
    active: stage

  config:
    import: optional:classpath:env.properties

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9090
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        enable.idempotence: true
        allow.auto.create.topics: false

    consumer:
      group-id: product-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: io.devground.product.*, io.devground.core.*
        allow.auto.create.topics: false

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ${S3_REGION}

  elasticsearch:
    uris: http://elasticsearch:9200
    connection-timeout: 10s
    socket-timeout: 60s

  ai:
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: product-vectors-index
        dimensions: 1536
        similarity: cosine
        embedding-field-name: content
    openai:
      api-key: ${OPEN_AI_API_KEY}
      base-url: https://api.openai.com/
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-ada-002

  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: product
    non-secure-port: 8086
    metadata-map:
      port: 8086

products:
  topic:
    image:
      push: product-images-push
      delete: product-images-delete
      push-dlt: ${products.topic.image.push}.DLT
      delete-dlt: ${products.topic.image.delete}.DLT

images:
  topic:
    push: images-push
    delete: images-delete
    processed: images-processed
    processed-dlt: ${images.topic.processed}.DLT

custom:
  kafka:
    config:
      topic-partitions: 1
      topic-replications: 1

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.batch: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
