spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/product_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: localhost