spring:
  application:
    name: dbay

  profiles:
    active: deploy

#  config:
#    activate:
#      on-profile: deploy

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  kafka:
    bootstrap-servers:
#      - kafka:9092
      - localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        enable.idempotence: true
        allow.auto.create.topics: false

    consumer:
      group-id: dbay-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: io.devground.dbay.*, io.devground.core.*
        allow.auto.create.topics: false

#    retry:
#      topic:
#        enabled: true
#        attempts: 5
#        delay: 1000
#        multiplier: 2.0
#        max-delay: 20000

  cloud:
    aws:
      s3:
        bucket: testBucket # 채울 것
      credentials:
        access-key: testAccessKey # 채울 것
        secret-key: testSecretKey # 채울 것
      region:
        static: testRegion # 채울 것

custom:
  kafka:
    config:
      topic-partitions: 1
      topic-replications: 1

carts:
  event:
    topic:
      user: carts-user-events
      name: carts-events
  command:
    topic:
      user: carts-user-commands
      name: carts-commands

orders:
  event:
    topic:
      name: orders-events
  command:
    topic:
      name: orders-commands

payments:
  event:
    topic:
      name: payments-events
  command:
    topic:
      name: payments-commands

deposits:
  event:
    topic:
      name: deposits-events
  command:
    topic:
      name: deposits-commands

products:
  topic:
    image:
      push: product-images-push
      delete: product-images-delete

images:
  topic:
    push: images-push
    delete: images-delete
    processed: images-processed

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.batch: INFO
