spring:
  application:
    name: dbay

  profiles:
    active: test

  jpa:
    hibernate:
#      default_batch_fetch_size: 500
#      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.batch: INFO