spring:
  application:
    name: dbay

  config:
    activate:
      on-profile: deploy

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  kafka:
    bootstrap-servers:
      #- kafka:9092
      - localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        enable.idempotence: true
        allow.auto.create.topics: false

    consumer:
      group-id: dbay-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: io.devground.dbay.*, io.devground.core.*
        allow.auto.create.topics: false

    retry:
      topic:
        enabled: true
        attempts: 5
        delay: 1000
        multiplier: 2.0
        max-delay: 20000

  cloud:
    aws:
      s3:
        bucket: testBucket # 채울 것
      credentials:
        access-key: testAccessKey # 채울 것
        secret-key: testSecretKey # 채울 것
      region:
        static: testRegion # 채울 것

deposits:
  event:
    topic:
      name: deposits-events
  command:
    topic:
      name: deposits-commandsS

custom:
  kafka:
    config:
      topic-partitions: 1
      topic-replications: 1

products:
  topic:
    image:
      push: products-image-push
      delete: products-image-delete

images:
  topic:
    push: images-push
    delete: images-delete


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.batch: INFO
