spring:
  cloud:
    gateway:
      routes:
        # 1) Swagger UI
        - id: user-swagger-ui
          uri: http://user:8082
          predicates:
            - Path=/user/swagger-ui/**
          filters:
            - StripPrefix=1

        - id: user-api-docs
          uri: http://user:8082
          predicates:
            - Path=/user/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: user-swagger-config
          uri: http://user:8082
          predicates:
            - Path=/user/v3/api-docs/swagger-config/**
          filters:
            - StripPrefix=1

        # 1) Swagger UI
        - id: dbay-swagger-ui
          uri: http://dbay:8080
          predicates:
            - Path=/dbay/swagger-ui/**
          filters:
            - StripPrefix=1

        - id: dbay-api-docs
          uri: http://dbay:8080
          predicates:
            - Path=/dbay/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: dbay-swagger-config
          uri: http://dbay:8080
          predicates:
            - Path=/dbay/v3/api-docs/swagger-config/**
          filters:
            - StripPrefix=1

        - id: deposits
          uri: lb://DBAY
          predicates:
            - Path=/api/deposits/**
          filters:
            - CustomAuthFilter

        - id: carts
          uri: lb://DBAY
          predicates:
            - Path=/api/carts/**
          filters:
            - CustomAuthFilter

        - id: products
          uri: lb://DBAY
          predicates:
            - Path=/api/products/**
          filters:
            - CustomAuthFilter

        - id: orders
          uri: lb://DBAY
          predicates:
            - Path=/api/orders/**
          filters:
            - CustomAuthFilter

        - id: payments
          uri: lb://DBAY
          predicates:
            - Path=/api/payments/**
          filters:
            - CustomAuthFilter

        - id: settlements
          uri: lb://DBAY
          predicates:
            - Path=/api/settlements/**
          filters:
            - CustomAuthFilter