#server:
#  port: 8000
#
#logging:
#  level:
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.cloud.gateway.filter: TRACE
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka:8761/eureka/
#
#spring:
#  application:
#    name: api-gateway
#
#  cloud:
#    gateway:
#      globalcors:
#        add-to-simple-url-handler-mapping: true
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins:
#              - "https://dbay.site"
#              - "https://www.dbay.site"
#              - "http://localhost:8000"
#              - "http://localhost:8080"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#            allowCredentials: true
#
#      routes:
#        - id: user-swagger-ui
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user/swagger-ui/**
#          filters:
#            - StripPrefix=1
#
#        - id: user-api-docs
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user/v3/api-docs/**
#          filters:
#            - StripPrefix=1
#
#        - id: user-swagger-config
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user/v3/api-docs/swagger-config/**
#          filters:
#            - StripPrefix=1
#
#        # 1) Swagger UI
#        - id: dbay-swagger-ui
#          uri: lb://DBAY
#          predicates:
#            - Path=/dbay/swagger-ui/**
#          filters:
#            - StripPrefix=1
#
#        - id: dbay-api-docs
#          uri: lb://DBAY
#          predicates:
#            - Path=/dbay/v3/api-docs/**
#          filters:
#            - StripPrefix=1
#
#        - id: dbay-swagger-config
#          uri: lb://DBAY
#          predicates:
#            - Path=/dbay/v3/api-docs/swagger-config/**
#          filters:
#            - StripPrefix=1
#
#        - id: adminCategories
#          uri: lb://DBAY
#          predicates:
#            - Path=/dbay/api/admin/categories/**
#          filters:
#            - StripPrefix=1
#            - CustomAuthFilter
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
