spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # 1) Swagger UI
            - id: user-swagger-ui
              uri: http://localhost:18080
              predicates:
                - Path=/user/swagger-ui/**
              filters:
                - StripPrefix=1

            - id: user-openapi
              uri: http://localhost:18080
              predicates:
                - Path=/v3/api-docs/**
                - Header=Referer, .*/user/swagger-ui/.*

            # 1) Swagger UI
            - id: dbay-swagger-ui
              uri: http://localhost:8080
              predicates:
                - Path=/dbay/swagger-ui/**
              filters:
                - StripPrefix=1

            - id: dbay-openapi
              uri: http://localhost:8080
              predicates:
                - Path=/v3/api-docs/**
                - Header=Referer, .*/dbay/swagger-ui/.*


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/