services:

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
#    depends_on:
#      - gateway


  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: R00t!2025@Secure1
      MYSQL_USER: mysqlId
      MYSQL_PASSWORD: mysqlPwd
      MYSQL_DATABASE: dbay_db
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init.sql


  mariadb:
    image: mariadb:11.3
    container_name: maria
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: R00t!2025@Secure2
      MARIADB_USER: mariaId
      MARIADB_PASSWORD: mariaPwd
      MARIADB_DATABASE: dbay_user
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - ./maria-data:/var/lib/mysql
      - ./init-mariadb.sql:/docker-entrypoint-initdb.d/init.sql


  kafka:
    image: apache/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9091"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9090,CONTROLLER://0.0.0.0:9091,EXTERNAL://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9090,EXTERNAL://43.201.80.95:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "ZWU1Y2JiNDctNDg3ZC4tNGY2Ny1iNzJh"
    restart: always


  elasticsearch:
    image: eddie1031/es:9.1.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch
      - cluster.name=cluster-es
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"


  logstash:
    image: logstash:9.1.3
    container_name: logstash
    ports:
      - "9600:9600"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/usr/share/logstash/logs:ro
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
      - "LOG_START_POSITION=end"
      - "ES_HOSTS=http://elasticsearch:9200"
    depends_on:
      - elasticsearch
    restart: unless-stopped


  kibana:
    image: kibana:9.1.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
