services:

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - gateway

  eureka:
    image: eclipse-temurin:21-jdk
    container_name: eureka
    working_dir: /app
    volumes:
      - ./eureka-server-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: [ "java", "-jar", "app.jar" ]
    ports:
      - "8761:8761"

  gateway:
    image: eclipse-temurin:21-jdk
    container_name: gateway
    working_dir: /app
    depends_on:
      - eureka
    volumes:
      - ./gateway-0.0.1-SNAPSHOT.jar:/app/app.jar
    environment:
      SPRING_PROFILES_ACTIVE: deploy
    command: [ "java", "-jar", "app.jar" ]
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: dbay_db
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root1234
      MARIADB_DATABASE: dbay_user
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - ./maria-data:/var/lib/mysql

  dbay:
    image: eclipse-temurin:21-jdk
    container_name: dbay
    working_dir: /app
    depends_on:
      - eureka
      - mysql
      - redis
      - kafka
    volumes:
      - ./dbay-0.0.1-SNAPSHOT.jar:/app/app.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dbay_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9090
      SPRING_PROFILES_ACTIVE: deploy
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_REGION: ${S3_REGION}
      TOSS_TEST_SECRET_KEY: ${TOSS_TEST_SECRET_KEY}
      external.openfeign-url: localhost:8080
    command: [ "java", "-jar", "app.jar" ]
    ports:
      - "8080:8080"

  user:
    image: eclipse-temurin:21-jdk
    container_name: user
    working_dir: /app
    depends_on:
      - mysql
      - redis
      - kafka
      - eureka
    volumes:
      - ./user-0.0.1-SNAPSHOT.jar:/app/app.jar
    environment:
      SPRING_PROFILES_ACTIVE: deploy
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/dbay_user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9090
      MAIL_EMAIL: ${MAIL_EMAIL}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    command: [ "java", "-jar", "app.jar" ]
    ports:
      - "8082:8082"

  kafka:
    image: apache/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9091"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9090,CONTROLLER://0.0.0.0:9091,EXTERNAL://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9090,EXTERNAL://43.201.80.95:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "ZWU1Y2JiNDctNDg3ZC4tNGY2Ny1iNzJh"
    restart: always

  elasticsearch:
    image: eddie1031/es:9.1.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch
      - cluster.name=cluster-es
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:9.1.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch

volumes:
  es-data:


