version: '3.8'

services:

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  eureka:
    image: eclipse-temurin:21-jdk
    container_name: eureka
    working_dir: /app
    volumes:
      - ./eureka-server-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: [ "java", "-jar", "app.jar" ]
    ports:
      - "8761:8761"

  gateway:
    image: eclipse-temurin:21-jdk
    container_name: gateway
    working_dir: /app
    depends_on:
      - eureka
    volumes:
      - ./gateway-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: [ "java", "-jar", "app.jar" ]
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: dbay_user
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root1234
      MARIADB_DATABASE: dbay_user
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - ./maria-data:/var/lib/mysql


  dbay:
    image: eclipse-temurin:21-jdk
    container_name: dbay
    working_dir: /app
    depends_on:
      - eureka
      - mysql
      - redis
      - kafka
    volumes:
      - ./dbay-0.0.1-SNAPSHOT.jar:/app/app.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dbay_user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      #SPRING_KAFKA_BOOTSTRAP_SERVERS: 43:201:80:95:9092
      SPRING_PROFILES_ACTIVE: local #수정
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    command: [ "java", "-jar", "app.jar" ]
    ports:
      - "8080:8080"


  user:
    image: eclipse-temurin:21-jdk
    container_name: user
    working_dir: /app
    depends_on:
      - mysql
      - redis
      - kafka
      - eureka
    volumes:
      - ./user-0.0.1-SNAPSHOT.jar:/app/app.jar
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dbay_user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: [ "java", "-jar", "app.jar" ]
    ports:
      - "8082:8082"

  kafka:
    image: apache/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9091"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9090,CONTROLLER://0.0.0.0:9091,EXTERNAL://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9090,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "ZWU1Y2JiNDctNDg3ZC4tNGY2Ny1iNzJh"
    restart: always

