version: '3.8'

services:

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  eureka:
    image: eclipse-temurin:21-jdk
    container_name: eureka
    working_dir: /app
    volumes:
      - ./eureka-server-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8761:8761"

  gateway:
    image: eclipse-temurin:21-jdk
    container_name: gateway
    working_dir: /app
    depends_on:
      - eureka
    volumes:
      - ./gateway-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: dbay_user
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  dbay:
    image: eclipse-temurin:21-jdk
    container_name: dbay
    working_dir: /app
    depends_on:
      - eureka
      - mysql
      - redis
    volumes:
      - ./user-0.0.1-SNAPSHOT.jar:/app/app.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dbay_user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    command: [ "java", "-jar", "app.jar" ]
    ports:
      - "8001:8001"

