name: dbay-test

services:

  redis:
    image: redis:7.2
    profiles: ["product"]
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka
    profiles: ["product"]
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - CLUSTER_ID=ZWU1Y2JiNDctNDg3ZC4tNGY2Ny1iNzJh
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9090,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9091
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  elasticsearch:
    image: eddie1031/es:9.1.3
    profiles: ["product"]
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch
      - cluster.name=cluster-es
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    image: kibana:9.1.3
    profiles: ["product"]
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch

  # 임시 보류
  eureka:
    image: eclipse-temurin:21-jdk
    profiles: ["apps"]
    working_dir: /app
    volumes:
      - ./eureka-server-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: [ "java", "-jar", "app.jar" ]
    ports:
      - "8761:8761"

  gateway:
    image: eclipse-temurin:21-jdk
    profiles: ["apps"]
    working_dir: /app
    depends_on:
      - eureka
    volumes:
      - ./gateway-0.0.1-SNAPSHOT.jar:/app/app.jar
    environment:
      SPRING_PROFILES_ACTIVE: stage
    command: [ "java", "-jar", "app.jar" ]
    ports:
      - "8000:8000"

  mariadb:
    image: mariadb:11.3
    restart: always
    profiles: ["apps"]
    environment:
      MARIADB_ROOT_PASSWORD: root1234
      MARIADB_DATABASE: dbay_user
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - ./maria-data:/var/lib/mysql

  dbay:
    image: eclipse-temurin:21-jdk
    profiles: ["apps"]
    working_dir: /app
    depends_on:
      - eureka
      - mysql
      - redis
      - kafka
    volumes:
      - ./dbay-0.0.1-SNAPSHOT.jar:/app/app.jar
      - ./logs:/app/logs
    environment:
      SPRING_PROFILES_ACTIVE: stage
    command: [ "java", "-jar", "app.jar" ]
    ports:
      - "8080:8080"

  user:
    image: eclipse-temurin:21-jdk
    profiles: ["apps"]
    working_dir: /app
    depends_on:
      - mysql
      - redis
      - kafka
      - eureka
    volumes:
      - ./user-0.0.1-SNAPSHOT.jar:/app/app.jar
    environment:
      SPRING_PROFILES_ACTIVE: stage
    command: [ "java", "-jar", "app.jar" ]
    ports:
      - "8082:8082"