server:
  port: 8086

spring:
  application:
    name: settlement

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  batch:
    jdbc:
      initialize-schema: never

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        enable.idempotence: true
        allow.auto.create.topics: false

    consumer:
      group-id: dbay-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: io.devground.dbay.*, io.devground.core.*
        allow.auto.create.topics: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: settlement
    non-secure-port: 8086
    metadata-map:
      port: 8086

deposits:
  event:
    topic:
      name: deposits-events
  command:
    topic:
      name: deposits-commands

settlements:
  event:
    topic:
      name: settlements-events

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.batch: INFO

external:
  openfeign-url: http://localhost:8080

custom:
  kafka:
    config:
      topic-partitions: 1
  batch:
    chunk:
      size: 100
    skip:
      limit: 10
    retry:
      limit: 3
  settlement:
    rate: 0.95
