apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
data:
  # 인프라 주소 (환경별로 다름)
  SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb-user:3306/dbay_user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9090"


