apiVersion: apps/v1

kind: Deployment

metadata:
  name: db-mysql
  labels:
    app: db-mysql

spec:

  selector:
    matchLabels:
      app: db-mysql

  template:
    metadata:
      name: db-mysql
      labels:
        app: db-mysql

    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql-configmap


---
apiVersion: apps/v1

kind: Deployment

metadata:
  name: db-maria
  labels:
    app: db-maria

spec:

  selector:
    matchLabels:
      app: db-maria

  template:
    metadata:
      name: db-maria
      labels:
        app: db-maria

    spec:
      containers:
        - name: maria
          image: maria
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: maria-configmap


---
apiVersion: apps/v1

kind: Deployment

metadata:
  name: db-mongo
  labels:
    app: db-mongo

spec:

  selector:
    matchLabels:
      app: db-mysql

  template:
    metadata:
      name: db-mysql
      labels:
        app: db-mysql

    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql-configmap





