apiVersion: v1

kind: Service

metadata:
  name: db-mysql

spec:

  selector:
    app: db-mysql

  ports:
    - targetPort: 3306
      port: 3306

---
apiVersion: v1

kind: Service

metadata:
  name: db-maria

spec:

  selector:
    app: db-maria

  ports:
    - targetPort: 3306
      port: 3306

---
apiVersion: v1

kind: Service

metadata:
  name: db-mongo

spec:

  selector:
    app: db-mongo

  ports:
    - targetPort: 27017
      port: 27017