apiVersion: apps/v1

kind: Deployment

metadata:
  name: postgresql-deposit
  labels:
    app: postgresql-deposit

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-deposit

  template:
    metadata:
      name: postgresql-deposit
      labels:
        app: postgresql-deposit

    spec:
      containers:
        - name: postgresql-deposit
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: depositdb-configmap
            - secretRef:
                name: depositdb-secret
