apiVersion: apps/v1

kind: Deployment

metadata:
  name: postgresql-order
  labels:
    app: postgresql-order

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-order

  template:
    metadata:
      name: postgresql-order
      labels:
        app: postgresql-order

    spec:
      containers:
        - name: postgresql-order
          image: postgres
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: orderdb-configmap
            - secretRef:
                name: orderdb-secret