apiVersion: apps/v1

kind: Deployment

metadata:
  name: mysql-payments
  labels:
    app: mysql-payments

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-payments

  template:
    metadata:
      name: mysql-payments
      labels:
        app: mysql-payments

    spec:
      containers:
        - name: mysql-payments
          image: mysql
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: paymentsdb-secret