apiVersion: apps/v1

kind: Deployment

metadata:
  name: mysql-payment
  labels:
    app: mysql-payment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-payment

  template:
    metadata:
      name: mysql-payment
      labels:
        app: mysql-payment

    spec:
      containers:
        - name: mysql-payment
          image: mysql
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: paymentdb-configmap
            - secretRef:
                name: paymentdb-secret