apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-user
  labels:
    app: mariadb-user

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-user

  template:
    metadata:
      name: mariadb-user
      labels:
        app: mariadb-user

    spec:
      containers:
        - name: mariadb-user
          image: mariadb:11
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mariadb-secret
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script
          configMap:
            name: mariadb-init-script

